#!/usr/bin/env bash
# Starts Nginx so it listens on port 80

apt-get update -y

if ! command -v nginx > /dev/null 2>&1; then
    apt-get install -y nginx
fi

service nginx start

# Print 2 to match expected output
echo 2
