#!/usr/bin/env bash
# Install nginx, configure default site to serve required content, and restart nginx

apt-get update -y
apt-get install -y nginx

sed -i 's|root .*;|root /var/www/html;|' /etc/nginx/sites-enabled/default
sed -i 's/index .*;/index index.html index.htm;/' /etc/nginx/sites-enabled/default

echo "Holberton School for the win!" > /var/www/html/index.html
chown www-data:www-data /var/www/html/index.html
chmod 644 /var/www/html/index.html

service nginx restart
