#!/usr/bin/env bash
# Script to configure a custom 404 error page

# Install Nginx
apt-get update
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update the Nginx config to use the custom 404 page
sed -i "/server_name _;/a \\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx
